name: Build Geode Mod

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android32
            target: Android32
          - name: Android64
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # 'given' = use whatever version is set in mod.json ("geode": "5.7.1")
          sdk: given
          target: ${{ matrix.config.target }}
          combine: true

  package:
    name: Package builds (android32 + android64 -> single .geode)
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: floating-menu-mod
          path: ${{ steps.build.outputs.build-output }}
